<center>
<h1>Lecture 3: Jupyter and IPython</h1>
<h2>预测分析</h2>
<h3>中科大管理学院</h3>
</center> 

# 本章概要

目标：对数据分析和处理常用的两个库进行介绍

1. NumPy (matrixes)

2. Pandas (tables)

# Numerical Python (NumPy)

* 科学计算的基础性package <!--%(many packages are based on these functionality), building block for other packages such as pandas-->
* 提供了
  * 数组、矩阵的处理 <!--%(python provide a flexible though inefficient implementation)-->
	* ndarray 具有相同类型和大小的项目的多维容器，N维数组对象，n-dimensional arrary
  * 与其他程序语言兼容
  * 读写数据的工具
  * 执行Linear algebra, Probability, Signal processing, 等领域的常用算法


# ndarray
* N维数组对象，一系列同类型数据的集合，以0下标为开始进行集合中元素的索引；ndarray中的每个元素在内存中都有相同存储大小的区域

* 创建数组:  np.array([1,3]), np.zeros(3), np.zeros((3,2)), np.ones(3), np.zeros\_like(a), np.eye(3), np.empty(3), np.arange(8), np.arange(1,10,2), a.copy()
		
* 特征: shape (维度), dtype (数据类型对象)
		
* [Data types](https://docs.scipy.org/doc/numpy/user/basics.types.html): integers, floating point numbers, boolean, strings, datetime, timedelta ([time difference](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html))

* 精度损失: 0.1+0.2+0.3+0.3+0.1==1 versus np.isclose(0.1+0.2+0.3+0.3+0.1,1)， 源码：isclose(a,b, *, rel_tol=1e-09, abs_tol=0.0),rel_tol：相对于输入值的大小，被认为是“接近”的最大差异，abs_tol:无论输入值的大小，被认为“接近”的最大差异，本质算法为 abs(a-b) <= max(rel_tol * max(abs(a), abs(b)), abs_tol)
* 类型设置（casting）: a.astype('int')			

# 生成arrays

In [2]:
import numpy as np  # import package

In [3]:
a = np.array([1, 31, 2])
print(a)

[ 1 31  2]


In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.dtype # the function array tries to infer the type

dtype('int64')

In [7]:
a = np.array([1, 31, 2.0])
a.dtype

dtype('float64')

### 创建多维array

In [8]:
a = np.array([[1,3,2,5],[9,7,6,4]])
print(a)

[[1 3 2 5]
 [9 7 6 4]]


In [9]:
a.shape

(2, 4)

In [10]:
a.dtype

dtype('int64')

### 创建标准化array

In [7]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.ones((3,3)) # array of 1s

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.empty(3) # uninitialized arrays (should not assume anything about these values)

array([3.58778387e-316, 0.00000000e+000, 4.94065646e-324])

In [10]:
np.arange(8) # initialize array to a sequence

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
np.arange(1,10,2) # increments of two

array([1, 3, 5, 7, 9])

In [12]:
a.copy() # returns a copy of an array

array([ 1., 31.,  2.])

# 数据类型

### Numerics

In [13]:
np.array([1,3,2]).dtype

dtype('int32')

In [14]:
np.array([1,3,0],dtype="int8")

array([1, 3, 0], dtype=int8)

In [15]:
np.array([1,3,2],dtype="int64")

array([1, 3, 2], dtype=int64)

In [16]:
b = np.array([1,3,2],dtype="float")
print(b)
print(b.dtype)

[1. 3. 2.]
float64


### 精度损失

In [17]:
0.1+0.2+0.3+0.3+0.1

1.0000000000000002

In [18]:
0.1+0.2+0.3+0.3+0.1==1.0

False

In [19]:
np.isclose(0.1+0.2+0.3+0.3+0.1,1.0)

True

### 布尔值

In [20]:
np.array([True, False, True])

array([ True, False,  True])

In [21]:
np.array([1, 0, 1],dtype="bool")

array([ True, False,  True])

### 字符

In [22]:
np.array(['hello', 'world'], dtype='string_')

array([b'hello', b'world'], dtype='|S5')

In [23]:
np.array(['hello', 'world'], dtype='U') # U - Unicode; U5 - 5 元素位长 数据大小

array(['hello', 'world'], dtype='<U5')

In [3]:
np.array(['hello', 'world', '和平'], dtype='string_') # expect an error

UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

In [25]:
np.array(['hello', 'world', '和平'], dtype='U')

array(['hello', 'world', '和平'], dtype='<U5')

### 类型设置

In [26]:
string_array = np.array(['1.25', '-9.6'])

In [27]:
string_array

array(['1.25', '-9.6'], dtype='<U4')

In [31]:
string_array.astype(np.float)
# try string_array.astype(np.int)

array([ 1.25, -9.6 ])

In [29]:
string_array.astype(np.float).astype(np.int)

array([ 1, -9])

# Vecterized Operations
* 数组的运算
	* 执行速度快 <!--% numpy implementation is typically faster than python loops-->
	* 可读性强（不需要循环） <!--% no need for loops-->
* 数组运算符: a+b, a-b, a*b
* 标量运算符（Operations with scalars）: a+2, a\*2, a\*\*2, 2/a, -2/a
* 特殊值: np.nan, np.inf, -np.inf, np.isnan(a), np.isinf(a), np.isfinite(a)	

# Vectorized Operations - cont.

* Math: a.max(), a.min(), a.std(), a.sum(), a.prod(), a.argmax(), a.argmin(), a.cumsum(), a.cumprod(), np.abs(a), np.sqrt(a), np.sin(a), np.sign(a)
* Sort (inplace): a.sort()
* Boolean arrays:  ~b1, b1|b2, b1&b2, b1==b2, b.all(), b.any(), a<3, a==3, a!=3, np.array_equal(b1,b2), np.where(a%3==0, 0, 1)
* Set operations:  np.unique(a), np.intersect1d(a,b), np.union1d(a,b), np.in1d(a,b), np.setdiff1d(a,b)

### Operation between arrays

In [1]:
a = np.array([-1,0,1])
b = np.array([4,5,6])

NameError: name 'np' is not defined

In [ ]:
a+b

In [ ]:
a*b

In [ ]:
a-b

### Operations with scalars

In [ ]:
a+2

In [ ]:
a*2

In [ ]:
a**2

In [ ]:
a

In [ ]:
2/a

### Special values: nan, inf

In [ ]:
-2/a

In [ ]:
np.sqrt(a)

In [ ]:
np.inf

In [ ]:
# test for inf
print(np.isinf(np.inf))
print(np.isinf(-np.inf))
print(np.isinf(np.nan))
print(np.isinf(1))

### Special values: nan, inf - cont.

In [ ]:
# test for nan
print(np.isnan(np.inf))
print(np.isnan(-np.inf))
print(np.isnan(np.nan))
print(np.isnan(1))

In [ ]:
# test for finiteness (not inf nor nan)
print(np.isfinite(np.inf))
print(np.isfinite(-np.inf))
print(np.isfinite(np.nan))
print(np.isfinite(1))

In [ ]:
# disable warnings
import warnings
warnings.filterwarnings('ignore')
#warnings.filterwarnings('default') # enable warnings

### Math operations

In [ ]:
a = np.array([1,3,4,2,1])

In [ ]:
a.max() # value of the maximal element (compare with lists)

In [ ]:
a.min() # value of minimal element

In [ ]:
a.mean() # average

In [ ]:
a.std() # standard deviation

In [ ]:
a.sum() # sum elements

### Boolean arrays

In [4]:
b1 = np.array([True, False, False])
b2 = np.array([True, False, True])

In [5]:
b1 & b2 # logical AND (in Python we used 'and')

array([ True, False, False])

In [6]:
b1 | b2 # logical OR (in Python we used 'or')

array([ True, False,  True])

In [7]:
~b1

array([False,  True,  True])

In [8]:
b1==b2

array([ True,  True, False])

In [9]:
(b1==b2).all() # test if all array values are True

False

In [10]:
np.array([1,2,3])==[1,2,3] # test if two arrays are equal

array([ True,  True,  True])

In [11]:
(np.array([1,2,3])==[1,2,3]).all() # '==' returns a vector

True

In [12]:
(b1==b2).any() # test if all there exists a True value in array

True

### Set operations

In [13]:
a = np.array([1,3,2,1,2,4])
b = [2,5]

In [14]:
np.unique(a)

array([1, 2, 3, 4])

In [15]:
np.intersect1d(a,b)

array([2])

In [16]:
np.union1d(a,b)

array([1, 2, 3, 4, 5])

In [17]:
np.in1d(a,b)

array([False, False,  True, False,  True, False])

In [19]:
np.in1d(b,a)

array([ True, False])

In [18]:
np.setdiff1d(a,b)

array([1, 3, 4])

# 练习 1
1. 创建一个array，含有Fibonaci series 
(https://en.wikipedia.org/wiki/Fibonacci_number)中的前20个数
2. 创建一个array，含有上述series中每个数值的平方值
（squared values of each number in the series）
3. 创建一个array，显示series中每个数值是否为偶数
(hint: the operator % computes the remainder of a division, e.g., 3%2=1)
4. 创建一个array，显示series中每个元素的倒数第一个数字(e.g., for 135 return 5)
5. 创建一个array，显示series中每个元素的倒数第二个数字(e.g., for 135 return 3)

In [ ]:
# write solution here


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
___

# Indexing
* 起始值为 0
* [Basic indexing](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#basic-slicing-and-indexing)
	* 数字或片对象（slice objects） 1:3:10
	* 例: a[0,:], a[-1,:], a[:,1], b = a[1:3,0:3:2]
	* Returns a view
		
* [Integer array indexing](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html\#integer-array-indexing) (using lists of indexes)
	* 抽取数值:  a[[1],:], a[[-1],:],a[:,[2,3]], a[:,[3,2]], a[[0,1],[3,2]], a[np.ix\_([0,1],[3,2])]
	* 设置数值:  a[:,[3,2]] = 999	
	* Returns a copy	


* [Boolean indexing](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#boolean-array-indexing) (using boolean array)	<!--% specify intervals-->
	
	* 用index创建一个1维array copy: 			
			x=a[a%3==0], x=a[(a%2==0)&(a>=4)]
	* 设置数值: a[a%3==0]=999
* 基于轴向（横纵）的运算: a.sum(), a.sum(axis=0), a.sum(axis=1), a.std(axis=0), sorting, etc.   1-跨列  0-跨行				

# Indexing

In [1]:
import numpy as np
a = np.array([10,20,30,40])

In [2]:
a[0]

10

In [3]:
a[1]

20

In [4]:
a[-1]

40

In [5]:
a[1:3]

array([20, 30])

### Basic Slicing and Indexing

In [8]:
a = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [9]:
a[0,:] # row 0

array([1, 2, 3, 4])

In [10]:
a[-1,:] # last row, try -2

array([10, 11, 12, 13])

In [11]:
a[:,1] # column 1

array([ 2,  6, 11])

In [12]:
b = a[0:7,0:2] # b is a view - use a[0:7,0:2].copy() to return a copy
b

array([[ 1,  2],
       [ 5,  6],
       [10, 11]])

### Basic Slicing and Indexing

In [43]:
b.shape

(3, 2)

In [44]:
b[0,0]=999 # b is a view, changes in b affect a

In [45]:
b

array([[999,   2],
       [  5,   6],
       [ 10,  11]])

In [46]:
a 

array([[999,   2,   3,   4],
       [  5,   6,   7,   8],
       [ 10,  11,  12,  13]])

In [14]:
b=a[0:7,0:2].copy()
b

array([[ 1,  2],
       [ 5,  6],
       [10, 11]])

In [17]:
b[0,0]=999
b
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [47]:
a[0,:]

array([999,   2,   3,   4])

In [48]:
a = np.arange(50).reshape((5,10))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [49]:
a[1:5:2,0:3:2] # Note:PRINTSCREEN

array([[10, 12],
       [30, 32]])

### Integer array indexing

In [50]:
a = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [51]:
a[[1],:] # row 1 (copy)

array([[5, 6, 7, 8]])

In [52]:
a[:,[2,3]] # columns 2,3

array([[ 3,  4],
       [ 7,  8],
       [12, 13]])

In [53]:
a[:,[3,2]] # column 3 and then 2

array([[ 4,  3],
       [ 8,  7],
       [13, 12]])

In [54]:
# setting values
a[:,[3,2]] = 999
a

array([[  1,   2, 999, 999],
       [  5,   6, 999, 999],
       [ 10,  11, 999, 999]])


### Boolean array indexing

In [55]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [56]:
# use boolean arrays to extract values
a[[True,True,False,False,True]]

array([1, 2, 5])

In [57]:
# use boolean arrays to set values
a[[True,True,False,False,True]] = 99
a

array([99, 99,  3,  4, 99])

### Multi-dimensional arrays

In [3]:
a = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [4]:
a.sum()

82

In [5]:
a.sum(axis=0) # 按列计算的和,本质上 应该是通过“行”的相加消除了“列”的信息

array([16, 19, 22, 25])

In [6]:
a.sum(axis=1) # 按行计算的和

array([10, 26, 46])

In [7]:
a.std(axis=0) # compute standard deviation of each column

array([3.68178701, 3.68178701, 3.68178701, 3.68178701])

In [8]:
a.std(axis=1) # compute the standard deviation of each row

array([1.11803399, 1.11803399, 1.11803399])

# 练习 2: Indexing 
 [magic square](https://en.wikipedia.org/wiki/Magic_square)中每个元素都不相等，且每一行、列及对角线的和均相等： 

<table class="wikitable" style="margin-left:auto;margin-right:auto;text-align:center;width:6em;height:6em;table-layout:fixed;">
<tr>
<td>4</td>
<td>9</td>
<td>2</td>
</tr>
<tr>
<td>3</td>
<td>5</td>
<td>7</td>
</tr>
<tr>
<td>8</td>
<td>1</td>
<td>6</td>
</tr>
</table>

1. 创建一个2维array表示上述square
2. 计算第一行之和
1. 计算所有行之和
2. 计算所有列之和 
3. 计算两个对角线的和
4. 写一个函数，可以输入一个matrix，并且测试这个matrix是不是magic square 
5. 用np.zeros((3,3))测试的你函数


In [ ]:
# write solution here



<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
___

# Math Packages
* [线性代数](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html)
	* 矩阵转置: a.T (more generally, use a.transpose() to vary axis order)
	* 点乘: np.dot(a,b)
	* 计算算法: norms, determinants, rank, eigenvalues, inverse, least-squares solution decomposition, solve linear equations, ...
* [概率](http://docs.scipy.org/doc/numpy/reference/routines.random.html)
	* 随机数产生: np.random.rand(3,2), randn(3,2), randint(3,2,-5,5), choice([1,10,20,7])
	* 排列一个序列或数组: permutation([1,2,3,4]), shuffle([1,2,3,4])
	* 函数分布: beta, binomial, gamma, poisson, ...
	* np.random.seed(8)
    
* [SciPy Library](http://docs.scipy.org/doc/scipy/reference/) - additional packages for scientific computing (optimization, signal processing, statistics, etc.)
    

### 概率

In [72]:
np.random.rand(3,2) # random variables from the uniform distribution

array([[0.21347256, 0.66217531],
       [0.44924176, 0.93511719],
       [0.76440981, 0.42280916]])

In [73]:
np.random.randn(3,2) # random variables from the standard normal distribution

array([[ 1.75443794, -0.18066631],
       [-0.4090904 ,  0.85459666],
       [ 1.56780809, -1.97317979]])

In [74]:
np.random.seed(8)
print(np.random.rand(3,2),'\n')
np.random.seed(8)
print(np.random.rand(3,2))

[[0.8734294  0.96854066]
 [0.86919454 0.53085569]
 [0.23272833 0.0113988 ]] 

[[0.8734294  0.96854066]
 [0.86919454 0.53085569]
 [0.23272833 0.0113988 ]]


# Manipulating arrays

* [Reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html): 
	* a.reshape((3,8)), a.reshape((3,8),order='f'), b.flatten(), b.flatten(order='f'), b.ravel() 
	* flatten - returns a copy; reshape, ravel - try to return a view
		
* [合并/连接数组 Concatenate](http://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html): 
	np.concatenate((a,b)), np.vstack((a,b)), <!--% visually, we put them one below the other, vertically-->
	np.concatenate((a,b),axis=1), np.hstack((a,b))
		
* [Split](http://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html): np.split(a,2,axis=0), np.split(a,2,axis=1), np.split(a,[2,7],axis=0)
		


# Manipulating arrays - cont.

	
* [Broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html): 对不同大小（维度）的arrays进行的操作
  * a+1 : 如果a是含有三个元素的array，broadcasting会把1扩展成[1,1,1]
  * a+b : broadcasting仅在以下情况有效：如果两个数组维数不相等，维数较低的数组的shape会从左开始填充1，直到和高维数组的维数匹配；如果两个数组维数相同，但某些维度的长度不同，那么长度为1的维度会被扩展，和另一数组的同维度的长度匹配；如果两个数组维数相同，但有任一维度的长度不同且不为1，则报错
  
|a.shape | (3,4) | (3,4) | (3,4) | (3,4) |
|-|-|-|-|
|b.shape | (4,)  | (3,)  | (3,1) | (3,2) |
|a+b Works?  | Yes   | No    | Yes   | No    |


### Reshape

In [18]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [19]:
b = a.reshape((4,6))
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [20]:
b.flatten() # default order is row-major

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
b.ravel() # returns view if possible (flatten returns copy)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Concatenation

In [22]:
a = np.arange(12).reshape((3,4))
b = a + 20
print(a,'\n')
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [24]:
np.concatenate((b,a)) # concatenate vertically

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
np.concatenate((a,b),axis=1) # concatenate horizontally

array([[ 0,  1,  2,  3, 20, 21, 22, 23],
       [ 4,  5,  6,  7, 24, 25, 26, 27],
       [ 8,  9, 10, 11, 28, 29, 30, 31]])

### Splitting

In [26]:
a = np.arange(24).reshape((4,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [76]:
list_of_arrays = np.split(a,2,axis=0) # 0 - 跨行，沿着每一列（或者行标签）向下执行

In [77]:
for a_ in list_of_arrays:
    print(a_,'\n')

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 



In [78]:
list_of_arrays = np.split(a,2,axis=1) # 1 - 跨列，沿着每一行（或者列标签）横向执行

In [79]:
for a in list_of_arrays:
    print(a,'\n')

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]] 

[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]] 



### Broadcasting

In [81]:
a = np.arange(4)
b = np.arange(4)*2
print('a:',a)
print('b:',b)

a: [0 1 2 3]
b: [0 2 4 6]


In [82]:
a+b

array([0, 3, 6, 9])

In [83]:
a + 1

array([1, 2, 3, 4])

In [84]:
c = np.arange(12).reshape((3,4))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
c + np.array([-1,-2,-3,-4])

array([[-1, -1, -1, -1],
       [ 3,  3,  3,  3],
       [ 7,  7,  7,  7]])

In [86]:
c + np.array([-1,-2,-3]) # expect error

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [87]:
c + np.array([-1,-2,-3]).reshape((3,1))

array([[-1,  0,  1,  2],
       [ 2,  3,  4,  5],
       [ 5,  6,  7,  8]])

In [88]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])